# Generated by Django 5.2.5 on 2025-12-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('cosme_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリー')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段(円)')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_point', models.TextField()),
                ('bad_point', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '☆☆☆☆★'), (2, '☆☆☆★★'), (3, '☆☆★★★'), (4, '☆★★★★'), (5, '★★★★★')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('teens', '～10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代～')], max_length=50)),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no', '回答しない')], max_length=50)),
                ('skin_type', models.CharField(choices=[('normal_skin', '普通肌'), ('dry_skin', '乾燥肌'), ('oily_skin', '脂性肌'), ('combination_skin', '混合肌'), ('sensitive_skin', '敏感肌')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
