# Generated by Django 5.2.5 on 2026-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age_group',
            field=models.CharField(blank=True, choices=[('teens', '10代'), ('twenties', '20代'), ('therties', '30代'), ('forties', '40代'), ('fivteies', '50代'), ('teens', '60代～')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('normal_skin', '普通肌'), ('dry_skin', '乾燥肌'), ('oily_skin', '脂性肌'), ('combination_skin', '混合肌'), ('sensitive_skin', '敏感肌')], max_length=20, null=True),
        ),
    ]
