# Generated by Django 5.2.5 on 2026-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review_age_group_review_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='age_group',
            field=models.CharField(blank=True, choices=[('teens', '～10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代～')], max_length=20, null=True),
        ),
    ]
