# Generated by Django 5.2.5 on 2026-01-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reviewfavorite_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFavorite',
        ),
    ]
