# Generated by Django 5.2.5 on 2026-01-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review_is_draft_alter_review_badpoint_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
