# Generated by Django 5.2.5 on 2026-01-25 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_productfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='review',
            name='skin_type',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, choices=[('teens', '～10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代～')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no', '回答しない')], max_length=50)),
                ('skin_type', models.CharField(blank=True, choices=[('normal_skin', '普通肌'), ('dry_skin', '乾燥肌'), ('oily_skin', '脂性肌'), ('combination_skin', '混合肌'), ('sensitive_skin', '敏感肌')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
