# Generated by Django 5.1.3 on 2026-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_review_age_group_remove_review_skin_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Cosmetic",
        ),
        migrations.AddField(
            model_name="review",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teens", "～10代"),
                    ("twenties", "20代"),
                    ("thirties", "30代"),
                    ("forties", "40代"),
                    ("fifties", "50代"),
                    ("sixties", "60代～"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal_skin", "普通肌"),
                    ("dry_skin", "乾燥肌"),
                    ("oily_skin", "脂性肌"),
                    ("combination_skin", "混合肌"),
                    ("sensitive_skin", "敏感肌"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="価格(円)"),
        ),
    ]
